name: Verify contract extension script

on: workflow_dispatch 


jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Verify contract extension
        uses: actions/checkout@v2

      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: "3.7"

      - name: Install dependencies
        run: pip3 install requests lxml beautifulsoup4 pandas

      - name: execute py script
        run: cd ./Scripts && python3 ./Contract_extensions.py
